name: CI

on:
  pull_request:
    branches:
      - '**'

jobs:
  check-tests-and-sonar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run UT/IT tests
        run: mvn verify

      - name: Upload JaCoCo UT XML report
        uses: actions/upload-artifact@v3
        with:
          name: jacoco-ut.xml
          path: ${{ github.workspace }}/target/site/jacoco-ut/jacoco.xml

      - name: Upload JaCoCo IT XML report
        uses: actions/upload-artifact@v3
        with:
          name: jacoco-it.xml
          path: ${{ github.workspace }}/target/site/jacoco-it/jacoco.xml

      - name: Analyze UT PR with JaCoCo
        id: jacoco-ut
        uses: madrapps/jacoco-report@v1.2
        with:
          paths: ${{ github.workspace }}/target/site/jacoco-ut/jacoco.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 0
          min-coverage-changed-files: 70
          title: UT code coverage
          update-comment: true
          debug-mode: false

      - name: Analyze IT PR with JaCoCo
        id: jacoco-it
        uses: madrapps/jacoco-report@v1.2
        with:
          paths: ${{ github.workspace }}/target/site/jacoco-it/jacoco.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 0
          min-coverage-changed-files: 0
          title: IT code coverage
          update-comment: true
          debug-mode: false
